### ISSUE TITLE
can't find device in devices list

### ISSUE THREAD

**Issue by henrykey** [syssi/xiaomiplug#21]
I added a xiaomi wifi socket in configuration.yaml following your instructions. configuration check is OK. But the xiaomi socket does not show up in device list. did I miss something or something wrong with me?

HassOS 5.8 in virtualbox, configuration.yaml is as following:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch:
  - platform: xiaomi_miio_plug
    name: Original Xiaomi Mi Smart WiFi Socket
    host: 192.168.23.149
    token: 98a11a5d7a1c404453b39af0fc30b952
    model: chuangmi.plug.m3
```
