### ISSUE TITLE
Add unique_id

### ISSUE THREAD

**Issue by santiacho** [syssi/xiaomiplug#31]
Is it possible to expose a `unique_id` to edit the switch via UI? 

My config
```yaml
switch:
  - platform: xiaomi_miio_plug
    unique_id: switch_aroma_entryway <--------------
    name: Aroma Entryway
    host: 192.168.xx.yyy
    token: ********************
    model: chuangmi.plug.m1
``` 

![Screenshot 2024-09-19 at 09 28 05](https://github.com/user-attachments/assets/7a1fd44c-e77e-4dd5-ba03-13edd97342f6)

![Screenshot 2024-09-19 at 09 30 25](https://github.com/user-attachments/assets/82a5090c-dc41-4782-9b82-cee94e31b763)
